#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid. Please follow conventional commit specification." >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{15,120}$"; then
    echo "Aborting commit. Your commit message length is invalid. Mininum 15 characters and Max 120 characters" >&2
    exit 1
fi
